using System;
using System.Net.Mail;

namespace Shop.Models
{
    public class Email
    {
        public string SenderEmailAddress { get; set; }
        public string SenderEmailPassword { get; set; }

        public string RecieverEmailAddress { get; set; }

        public string Message { get; set; }
        public int Key { get; set; }

        public Email()
        {
            /*
             *  https://myaccount.google.com/lesssecureapps
             */
            Message = "Your auto generate key is: " + Key;
        }

        public Email(string senderEmailAddress, string senderEmailPassword,
            string recieverEmailAddress, int key)
        {
            SenderEmailAddress = senderEmailAddress;
            SenderEmailPassword = senderEmailPassword;
            RecieverEmailAddress = recieverEmailAddress;
            Key = key;
            Message = "Your auto generate key is: " + Key;
        }

        public void SendEmail()
        {
            Console.WriteLine($"Your AutoGenerated Key is : {Key}");
            try
            {
                //MailAddress from = new MailAddress(SenderEmailAddress);
                //MailAddress to = new MailAddress(RecieverEmailAddress);
                //MailMessage message = new MailMessage(from, to);
                //message.Subject = "Your Auto-Generated Token - J◢ ◤SE";
                //message.Body = $"Your Authentication Token is: {Key} \r\n" +
                //    "If you didn't try to log in change your email password now!\r\n" +
                //    "This is a test. Don't Change your password I am testing the website";

                //// host, port, and credentials.
                //string host = "smtp.gmail.com";
                //int port = 587;

                //SmtpClient client = new SmtpClient(host, port);
                //bool ssl = true;

                //client.UseDefaultCredentials = false;
                //client.Credentials = new System.Net.NetworkCredential(SenderEmailAddress, SenderEmailPassword);
                //client.EnableSsl = ssl;
                //client.DeliveryMethod = SmtpDeliveryMethod.Network;
                //client.UseDefaultCredentials = true;

                //client.Send(message);

            } catch(Exception)
            {
                //Console.WriteLine($"Something went wrong Email: {SenderEmailAddress}, Password: {SenderEmailPassword}");
            }
        }
    }
}
